services:
  core_backend:
    depends_on:
      - relational_db
      - redis
    environment:
      - POSTGRES_HOST=relational_db
  relational_db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - .core_backend.env
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_volume:
